const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('assets/js/uma-quest-export.js','utf8');
let mode='normal',attempts=[],opened=[],downloads=[];
const sandbox={window:{open:(...args)=>opened.push(args)},Image:class{},Map,Promise,Error,Blob,URL,Uint8Array,atob,setTimeout,clearTimeout,document:{fonts:{ready:Promise.reject(Error('font'))},body:{append(){}},createElement(tag){if(tag==='a')return{click(){downloads.push(this.download);},remove(){}};const canvas={width:0,height:0,getContext(){attempts.push([this.width,this.height]);return{scale(){},drawImage(){if(mode==='taint')throw Error('image');}};},toBlob(cb){cb(mode==='null'||mode==='taint'?null:new Blob(['png']));},toDataURL(){if(mode==='taint')throw Error('tainted');return 'data:image/png;base64,cG5n';}};return canvas;}}};
vm.createContext(sandbox);vm.runInContext(source,sandbox);const E=sandbox.window.UmaQuestExport;
(async()=>{
 assert.equal(typeof sandbox.File,'undefined');let blob=await E.render(1080,1350,()=>{});assert.equal(blob.size,3);
 mode='null';blob=await E.render(1080,1350,()=>{});assert.equal(blob.size,3,'null toBlob falls back to PNG data URL');
 mode='taint';attempts=[];await assert.rejects(E.render(1080,1350,(ctx,art)=>{if(art)ctx.drawImage();}));assert.deepEqual(attempts,[[1080,1350],[720,900],[720,900]]);
 // Rendering failure from optional artwork recovers on a clean canvas without artwork.
 mode='normal';attempts=[];blob=await E.render(1080,1350,(_,art)=>{if(art)throw Error('art failed');});assert.equal(blob.size,3);assert.equal(attempts.length,3);
 const message='確認用 #旅するうまさん\nhttps://example.test/quest';E.post(message);assert.equal(new URL(opened[0][0]).hostname,'x.com');assert.equal(new URL(opened[0][0]).searchParams.get('text'),message);assert.equal(opened[0][2],'noopener,noreferrer');
 const note={textContent:'',children:[],append(...items){this.children.push(...items);}};
 sandbox.navigator={userAgent:'iPhone',platform:'iPhone',maxTouchPoints:5};
 assert.equal(await E.save(blob,'record.png',note),'fallback','old iOS without File can open the image');
 assert.equal(note.children.at(-1).target,'_blank');assert.ok(note.children.at(-1).href.startsWith('blob:'));
 assert.equal(downloads.length,0,'iOS does not silently download into Files');
 sandbox.File=File;let payload,resolveShare;
 sandbox.navigator.canShare=({files})=>files[0].type==='image/png';
 sandbox.navigator.share=data=>{payload=data;return new Promise(resolve=>resolveShare=resolve);};
 const saving=E.save(blob,'record.png',note);
 assert.equal(payload.files[0].name,'record.png','share runs synchronously within the tap');
 assert.equal(await payload.files[0].text(),await blob.text());assert.equal(Object.keys(payload).join(','),'files');
 assert.equal(await E.post(message,note),undefined,'a second tap cannot open another share sheet');
 resolveShare();assert.equal(await saving,'shared');assert.ok(!note.textContent.includes('保存しました'));
 sandbox.window.UmaQuestConfig={url:'https://example.test/quest'};
 const posting=E.post(message,note);assert.equal(payload.text,'確認用 #旅するうまさん');assert.equal(payload.url,'https://example.test/quest');assert.equal(Object.keys(payload).join(','),'text,url','native share receives the web URL without duplicate text or an image attachment');resolveShare();await posting;
 const openedBefore=opened.length;
 sandbox.navigator.share=()=>Promise.reject(Object.assign(Error('cancel'),{name:'AbortError'}));
 assert.equal(await E.save(blob,'record.png',note),'cancelled');assert.equal(await E.post(message,note),'cancelled');assert.equal(note.textContent,'');assert.equal(downloads.length,0);assert.equal(opened.length,openedBefore);
 sandbox.navigator.share=()=>Promise.reject(Object.assign(Error('blocked'),{name:'NotAllowedError'}));
 assert.equal(await E.save(blob,'record.png',note),'fallback');assert.equal(await E.post(message,note),'fallback');assert.equal(opened.length,openedBefore,'failed share needs a fresh user click for web fallback');assert.equal(new URL(note.children.at(-1).href).hostname,'x.com');
 sandbox.navigator.platform='MacIntel';sandbox.navigator.userAgent='Macintosh';sandbox.navigator.maxTouchPoints=5;sandbox.navigator.share=data=>{payload=data;return Promise.resolve();};assert.equal(await E.post(message,note),'shared','iPad desktop UA uses native sharing');
 sandbox.navigator.userAgent='Windows';sandbox.navigator.platform='Win32';sandbox.navigator.maxTouchPoints=0;
 sandbox.setTimeout=(fn,ms)=>{const timer=setTimeout(fn,ms);timer.unref();return timer;};
 assert.equal(await E.save(blob,'desktop.png',note),'download');assert.equal(downloads.at(-1),'desktop.png');assert.equal(await E.post(message,note),'browser');
 console.log('PASS: PNG/font fallbacks, iOS file and caption sharing, original PNG bytes, cancellation, double-tap guard, manual failure fallback, iPad detection, desktop download and X intent.');
})().catch(e=>{console.error(e);process.exitCode=1;});
